# Recommendation

* Last updated 20201128SUN0715 20201014Reverted 20191126TUE1106

## S.1 학습내용

### S.1.1 목표

* 내용기반 추천, 협업 추천을 프로그래밍으로 구현
* matrix factorization

### S.1.2 목차

* S.2 문제의 이해
* S.3 추천이란
* S.4 collaborative filtering 방법
* S.4.1 Neighborhood Methods
* S.4.2 Latent Factor Methods
* S.5 유사도
* S.5.1 Eculdean distance
* S.5.2 Manhatan distance
* S.5.3 L-form
* S.5.4 cosine 유사도
* S.5.5 similarity
* S.6 영화평가
* S.7 인지도 기반 추천
* S.8 경사도 하강 Matrix Factorization
* S.8.1 알고리즘
* S.8.2 풀어보기
* S.8.3 프로그램으로 풀어보기
* S.8.4 Spark
* S.10 SVD
* 문제 S-5: ALS 알고리즘으로 영화 추천

## S.2 문제의 이해

영화를 본다고 하자.
어떤 영화를 관람할지, 먼저 관람한 사람들의 **리뷰** 또는 **평점**을 보고 결정하기도 한다.
영화뿐만 아니라 음악, 책, 어떤 제품도 먼저 구매하거나 경험한 사람들의 평점이 구매에 영향을 미칠 수 있다.
평점이 높은 영화를 추천한다면, 그 영화를 선택하는데 매우 유용한 정보가 될 것이다.
일반적인 **인기도**에 따른 추천도 좋지만,
**내가 좋아하는, 개인의 특성에 맞는** 상품이나 콘텐츠를 추천할 수 있다면 더욱 효과적이겠다.
어떻게 하면 **내가 좋아할만한** 영화를 선택할 수 있을까?
**내가 듣고 싶은** 음악을 선택할 수 있을까?
이런 문제를 추천할 수 있는 방법에 대해 학습해보자.

## S.3 추천이란

### 인기도 기반
많은 사람들이 선호하는 상품을 추천하는 것이다. 
예를 들어 영화를 추천할 경우, 많이 본 영화 또는 평점이 높은 영화를 추천하는 것이다.
자신이 속한 연령대, 성별로 구분하여 인기 순위가 높은 영화를 추천하면 **세분화**되겠지만, **개인의 특성이 속한 그룹과 동일하다고 보기는 어렵다**.

### 상품기반
**내용기반 추천 Content Filtering**은 상품간에 유사도를 계산하여 추천을 하는 것이다.
영화의 예를 들면, 장르, 출연배우, 인기도 등에 따라 서로 유사한 영화를 선정하여 추천한다.

### 사용자 기반
**협업 추천 Collaborative Filtering**은 사용자와 상품 간 상호관련성에 따라 추천을 하게 된다.
사용자 A가 노래 P, Q, R을 좋아한다고 하자. 사용자 B도 영화 P, Q를 좋아한다고 하자. 그러면 사용자 A와 B는 서로 취향이 유사하고, 아직 관람하지 않은 영화 R을 추천하게 되는 것이다.


## S.4 추천 방법

### S.4.1 Neighborhood Methods

이 협업 추천 collaborative filtering 방법은 사용자의 상품 선호도에 대한 유사도가 서로 비슷한 사용자를 찾아서 추천한다.

단계:
* 유사도가 높은 사용자, **이웃 neighbors**를 식별
* 그 neighbors가 좋아하는 상품을 추천

### S.4.2  Matrix Factorization

앞서 사용자 또는 제품 간에 가까운 유사도를 찾고 이런 이웃이 선택했거나 좋아했던 아이템을 추천하는데 반해,
Matrix Factorization은 **분해 모델**이라고 할 수 있다.
MF는 원래의 모델을 분리해내는 기법으로, 무엇인가 숨겨진 요인을 찾아서 2개 또는 그 이상으로 분리해내고, 이들을 곱하면 원래의 매트릭스가 산출되도록 한다.
즉,
* **original matrix**를 **u**, **i**로 분리하고
* 분리된 속성 **u** x **i**를 곱하여 원래의 **original matrix**를 산출할 수 있다.


예를 들어, 사용자 U1부터 U5, 상품 D1부터 D4가 있고, 사용자의 상품에 대한 평가점수가 있다고 하자.
그렇다면 다음 표가 완성될 수 있다.
이 표에 비어있는 평가점수를 채워 넣어야 한다.
비슷한 사용자끼리 서로 비슷한 점수를 넣는다고 가정하고
숨겨진 latent features를 유추하고 나면, 이를 통해서 빈 값을 채워넣을 수 있다.

```python
	D1	D2	D3	D4
U1	5	3	-	1
U2	4	-	-	1
U3	1	1	-	5
U4	1	-	-	4
U5	-	1	5	4
```

MF는 뭔가 **숨겨진 평가항목 latent features**이 있어서 사용자의 평가점수를 결정한다고 가정한다.
예를 들어, 두 사용자가 어떤 영화를 다 같이 좋아한다고 하자.
그 영화가 액션영화라고 하면 **장르가 숨겨진 속성**이 되고
이러한 latent features를 발견할 수 있다면, 사용자의 상품에 대한 평가점수를, 즉 원래의 평가점수를 알아낼 수 있다.


Latent Factor는 숨겨진 요인을 의미하고,
사용자 x 상품의 선호도를 이 숨겨진 요인으로 분해하고, 그 유사도에 따라 추천한다.
그렇다면 숨겨진 요인을 '왜 찾는지', '어떻게 찾는지' 의문이 생기게 된다.
숨겨진 요인을 찾는 이유를 이해하면, 찾는 방법에 대해서도 자연히 대답이 되겠다.
**사용자의 영화에 대한 평점이 완성된 형태로 있기 어렵고, 비워진 값이 많기** 때문이다.
원래의 모델, 즉 사용자가 상품에 대한 평점을 모아 놓은 Utility Matrix에는 결측 값이 많을 수 밖에 없다.
이와 같이 모델을 분해하면, 비워진 값을 채우기 때문에 요인, 즉 **숨겨진 요인을 추가해서 그 결측 값을 채울 수** 있고,
사용자의 평점을 완성할 수 있다는 의미이다.
이를 통해서 추천으로 사용하게 된다.
MF는 vector에 존재하는 빈 값을 해결하기 위해 제시된 해법으로 Netflix Prize Challenge 이후로 많이 쓰이고 있다.
(Koren, Y., Bell, R., & Volinsky, C., 2009, "Matrix factorization techniques for recommender systems," Computer, 8, 30-37.)

이 방법으로는:
* Principal Component Analysis
* SVG
* 교대 최소자승법 ALS Alternating Least Squares
latent vectors는 사용자와 상품 벡터가 있는데, 이를 하나씩 고정시키고 문제를 푸는 방식이다. 즉 하나씩 번갈아 학습을 한다.
먼저 상품 벡터를 고정시키고, 사용자 벡터에 대해 오류를 최소화하는 값을 구한다. 다음은 고정시켰던 상품 벡터에 대해 오류를 최소화한다. 이런 방식이 최적화될 때까지 반복한다. ALS는 나중에 우리가 배울 Spark에서 쓰이고 있다.
* 경사도 하강법: 반복을 통해서 오류가 최소가 되는 값을 찾아내는 방식으로 프로그램으로 구현해 볼 것이다.

## S.5 유사도

서로 취향이 비슷한 사람들끼리는 서로 좋아하는 것이 유사할 것이다.
예를 들어, 자신이 좋아하는 음식과 비슷한 취향을 가진 사람들을 찾아 그 사람들이 좋아하는 것을 추천하면 좋겠다.
취향이 비슷한 사용자를 찾는다고 하면, 유사도를 계산해야 한다.

### S.5.1 Eculdean distance

데이터 거리의 제곱을 계산한 값의 제곱근으로 구한다.

$\sqrt{\sum\limits_{i=1}^n (x_i - y_i)^2}$

In [1]:
import numpy as np

a=np.array([0,1,0,4,0])
b=np.array([0,4,0,2,3])
c=np.array([0,1,0,4,4])

In [4]:
from math import*
 
def euclideanDistance(x,y):
    return sqrt(sum(pow(a-b,2) for a, b in zip(x, y)))

print ("Euclidean Distance: {:.3f}".format(euclideanDistance(a,b)))

Euclidean Distance: 4.690


### S.5.2 Manhatan distance

거리의 절대 값

$\sum\limits_{i=1}^n |x_i - y_i|$

In [5]:
from math import *
 
def manhattanDistance(x,y): 
    return sum(abs(a-b) for a,b in zip(x,y))

print ("Manhattan Distance: {:.3f}".format(manhattanDistance(a,b)))

Manhattan Distance: 8.000


### S.5.3 L-form

$(\sum\limits_{i=1}^n |x_i - y_i|^p)^{\frac{1}{p}}$

p가 1이면 절대값 합계, 즉 L1이 되며, Manhatan distance와 같은 값이다.
p가 2일 경우에는 제곱합의 루트 L2가 되며, Eculdean distance과 동일하다.

numpy norm은 양수 값으로 만들어주는 함수를 말한다.
numpy norm으로 L-form을 계산할 수 있다.

1, 2, 3의 numpy norm은 각 절대 값을 더해서 계산된다.

$ |1| + |2| + |3| = 6$

In [6]:
x = np.array([1, 2, 3])
L1=np.linalg.norm(x, 1)
print ("L1: {:.3f}".format(L1))

L1: 6.000


In [7]:
L1=np.linalg.norm(a-b, 1)
print ("L1: {:.3f}".format(L1))

L1: 8.000


In [8]:
L2=np.sqrt(x[0]^2 + x[1]**2 + x[2]**2)
print ("L2: {:.3f}".format(L2))

L2: 3.742


In [9]:
L2=np.linalg.norm(a-b, 2)
print ("L2: {:.3f}".format(L2))

L2: 4.690


```norm()``` 함수의 default는 L2라서 생략할 수 있다.

In [10]:
np.linalg.norm(a-b)

4.69041575982343

### S.5.4 cosine 유사도

$\cos(\theta) = \frac {A \cdot B }{||A|| \cdot ||B||} = \frac {\sum_{i=1}^{n}{A_i B_i}}{{\sqrt {\sum_{i=1}^{n} A_i^{2}}}{\sqrt {\sum_{i=1}^{n} B_{i}^{2}}}}$

In [11]:
from math import *
 
def cosSimilarity(x,y): 
    numerator = sum(a*b for a,b in zip(x,y))
    denominator = sqrt(sum([a*a for a in x])) * sqrt(sum([a*a for a in y]))
    return round(numerator/float(denominator),4)

print ("Cossine Similarity: {:.3f}".format(cosSimilarity(a,b)))

Cossine Similarity: 0.540


In [12]:
cos_sim = np.dot(a, b)/(np.linalg.norm(a)*np.linalg.norm(b))
print ("Cossine Similarity: {:.3f}".format(cos_sim))

Cossine Similarity: 0.540


In [13]:
from scipy.spatial.distance import cosine

print (1 - cosine(a, b))

0.540452818933254


In [14]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity([a, b, c])

array([[1.        , 0.54045282, 0.71774056],
       [0.54045282, 1.        , 0.77580982],
       [0.71774056, 0.77580982, 1.        ]])

* 상관관계

* Jaccard

$\frac{A \cap B}{A \cup B}$

In [16]:
from math import *
 
def jaccardSimilarity(x,y): 
    intersection_cardinality = len(set.intersection(*[set(x), set(y)]))
    union_cardinality = len(set.union(*[set(x), set(y)]))
    return intersection_cardinality/float(union_cardinality)

print ("Jaccard Similarity: {:.3f}".format(jaccardSimilarity(a,b)))

Jaccard Similarity: 0.400


### S.5.5 correlation

$$
   r = \frac{\sum\limits_{i=1}^n (X_i - \bar{X})(Y_i -
   \bar{Y})}{\sqrt{\sum\limits_{i=1}^n (X_i - \bar{X})^2} \sqrt{\sum
   \limits_{i=1}^n (Y_i - \bar{Y})^2}}
$$

## S.6 영화 평가

### S.6.1 데이터 내려받기

MovieLens는 University of Minnesota에서 제공하는 프로젝트, [grouplens](https://grouplens.org/)이다.
영화평가 파일은 zip으로 되어 있다.

* Harper, F. M., & Konstan, J. A. (2016). The movielens datasets: History and context. ACM transactions on interactive intelligent systems (tiis), 5(4), 19.
* https://inclass.kaggle.com/c/movie

데이터는 4개의 CSV 파일로 구성되었다 ratings, movies, links and tags.
ratings 데이터는 100,836

movielens 사이트의 url에서 데이터를 직접 읽어오자.

In [5]:
import os
import urllib

ml_url = 'http://files.grouplens.org/datasets/movielens/ml-latest.zip'
ml_small_url = 'http://files.grouplens.org/datasets/movielens/ml-latest-small.zip'

```urllib.urlretrieve()``` 함수로 url에서 직접 읽어 주어진 파일명으로 저장한다. ```ml-latest.zip```와 ```ml-latest-small.zip``` 두 개의 파일이 있다.

In [7]:
ml_fname=os.path.join(os.getcwd(),'data','ml-latest.zip')
if(not os.path.exists(ml_fname)):
    print ("%s data does not exist! retrieving.." % ml_fname)
    ml_f=urllib.urlretrieve(ml_url,ml_fname)

In [8]:
ml_small_fname=os.path.join(os.getcwd(),'data','ml-latest-small.zip')
if(not os.path.exists(ml_small_fname)):
    print ("%s data does not exist! retrieving.." % ml_small_fname)
    ml_small_f=urllib.urlretrieve(ml_small_url,ml_small_fname)

```extractall()``` 함수는 ```data``` 디렉토리에 zip을 풀어서 저장한다.

In [ ]:
import zipfile

zipfiles=[ml_fname,ml_small_fname]
for f in zipfiles:
    zip = zipfile.ZipFile(f)
    zip.extractall('data')

압축한 파일을 살펴 보자. 각 파일의 내용을 ```head```로 읽어보자.

In [9]:
!ls data/ml-latest-small/

links.csv  movies.csv  ratings.csv  README.txt	tags.csv


In [10]:
!head data/ml-latest-small/links.csv

In [6]:
!head data/ml-latest-small/movies.csv

In [7]:
!head data/ml-latest-small/ratings.csv

In [8]:
!head data/ml-latest-small/tags.csv

### S.6.2 Pandas로 데이터 읽기

Pandas는 데이터를 분석하는 파이썬 라이브러리이다.
Dataframe은 엑셀과 같이 행과 열로 구성된 데이터 구조로서, 행과 열로 다양한 분석기능을 사용할 수 있다.

앞서 준비해 놓은 파일은 컴마로 데이터가 분리된 csv (comma separated values)이다.
```read_csv()```함수는 지정한 경로에서 csv 파일을 읽어온다.
경로는 현재 작업디렉토리를 의미하는 ```os.getcwd()```에서 시작하여, 접근하려는 디렉토리와 파일을 연속적으로 적어준다.
ml-latest는 데이터가 많아서 컴퓨터에 따라 분석에 제한이 될 수 있으므로, 축소판 ml-latest-small를 사용하기로 한다.

In [17]:
import pandas as pd
import os

#ratings = pd.read_csv(os.path.join(os.getcwd(),'data','ml-latest','ratings.csv'))
#movies = pd.read_csv(os.path.join(os.getcwd(),'data','ml-latest','movies.csv'))
ratings = pd.read_csv(os.path.join(os.getcwd(),'data','ml-latest-small','ratings.csv'))
movies = pd.read_csv(os.path.join(os.getcwd(),'data','ml-latest-small','movies.csv'))

사용자 평점과 영화파일이 잘 읽혀졌는지 첫 3행을 읽어보자.

In [18]:
ratings.head(3)

userId  movieId  rating   timestamp
0       1       16     4.0  1217897793
1       1       24     1.5  1217895807
2       1       32     4.0  1217896246

In [19]:
movies.head(3)

movieId                    title  \
0        1         Toy Story (1995)   
1        2           Jumanji (1995)   
2        3  Grumpier Old Men (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance

파일 컬럼의 행에 붙여진 속성 이름인 column header를 알아보자.
* ratings는 사용자ID, 영화ID, 사용자 평점, 평가일시로 구성되어 있다.
* movies는 영화ID, 영화제목, 장르 데이터를 가지고 있다.

In [20]:
ratings.columns.values

array(['userId', 'movieId', 'rating', 'timestamp'], dtype=object)

In [21]:
movies.columns.values

array(['movieId', 'title', 'genres'], dtype=object)

### S.6.3 영화 검색

#### 열 읽기

Dataframe은 행 row, 열 column으로 구성된 데이터 저장소이다.
먼저 열로 영화를 조회해 보자.
영화는 컬럼명 'title'로 제목을 검색하고, 그 컬럼의 첫번째를 읽어보자.

In [22]:
movies['title'][0]

'Toy Story (1995)'

영화제목에 'Toy Story'가 포함되었는지 검색해보자.
```movies['title'].str.contains()``` 함수는 **정규표현식**을 사용해서 영화제목에 문자열이 포함되었는지 확인한다.

In [23]:
movies[movies['title'].str.contains("Toy Story")==True]

movieId               title  \
0           1    Toy Story (1995)   
2496     3114  Toy Story 2 (1999)   
8599    78499  Toy Story 3 (2010)   

                                                genres  
0          Adventure|Animation|Children|Comedy|Fantasy  
2496       Adventure|Animation|Children|Comedy|Fantasy  
8599  Adventure|Animation|Children|Comedy|Fantasy|IMAX

정규식 **```\d```**는 숫자를 의미하는 메타문자이다.
```.\d+.*```는 어떤 한 문자(.), 이어서 숫자 1개 이상(\d+), 그리고 여러 문자 (.*)가 뒤 따르는 패턴을 찾게 된다.
따라서 Toy Story 속편 2, 3이 검색된다.
정규식 패턴 ```.\d*.*```는 숫자가 없어도 찾아낸다.

In [24]:
movies[movies['title'].str.contains("Toy Story.\d+.*")==True]

movieId               title  \
2496     3114  Toy Story 2 (1999)   
8599    78499  Toy Story 3 (2010)   

                                                genres  
2496       Adventure|Animation|Children|Comedy|Fantasy  
8599  Adventure|Animation|Children|Comedy|Fantasy|IMAX

#### 행으로 데이터 읽기

행 데이터는 인덱스로 검색할 수 있다. ```[시작 인덱스:끝 인덱스]```를 적어주면 해당하는 행을 출력할 수 있다.

In [25]:
movies[1:3]

movieId                    title                      genres
1        2           Jumanji (1995)  Adventure|Children|Fantasy
2        3  Grumpier Old Men (1995)              Comedy|Romance

두 명령어 **```loc```**, **```iloc```**를 사용할 수 있는데, 서로 비슷해서 조금 혼란스럽다.
우리가 다른 배열에서 사용하는 인덱스와 ```iloc```는 비슷하다.
즉 **```iloc``` 정수인덱스의 위치**로 검색한다. 1은 첫째 행을 의미한다.

In [26]:
movies.iloc[1] # first row

movieId                             2
title                  Jumanji (1995)
genres     Adventure|Children|Fantasy
Name: 1, dtype: object

In [27]:
movies.iloc[[2496,8599]]

movieId               title  \
2496     3114  Toy Story 2 (1999)   
8599    78499  Toy Story 3 (2010)   

                                                genres  
2496       Adventure|Animation|Children|Comedy|Fantasy  
8599  Adventure|Animation|Children|Comedy|Fantasy|IMAX

**```loc```**는 인덱스 **레이블**로 검색, 즉 인덱스의 레이블 값을 지칭한다.
인덱스가 레이블이면, 예를 들어 'x', 'y'이면 이해가 쉽겠지만, 아쉽게도 여기서는 레이블명이 숫자로 되어있다.
즉 인덱스가 1, 3은 첫번째, 세번째인 경우가 아니라, **인덱스 명이 1, 3**인 경우가 해당한다.

In [28]:
movies.loc[[1,3]]

movieId                     title                      genres
1        2            Jumanji (1995)  Adventure|Children|Fantasy
3        4  Waiting to Exhale (1995)        Comedy|Drama|Romance

In [29]:
movies.loc[[2496,8599]]

movieId               title  \
2496     3114  Toy Story 2 (1999)   
8599    78499  Toy Story 3 (2010)   

                                                genres  
2496       Adventure|Animation|Children|Comedy|Fantasy  
8599  Adventure|Animation|Children|Comedy|Fantasy|IMAX

loc은 레이블명을 사용한다고 했는데, 'title' 인덱스는 해당 컬럼을 조회한다.

In [30]:
movies.loc[[2496,8599],['title']]

title
2496  Toy Story 2 (1999)
8599  Toy Story 3 (2010)

### 반복문

**```iterrows()```** 함수는 Pandas의 ```Series``` 객체를 반환하기 때문에, 데이터프레임의 컬럼명으로 값을 조회할 수 있다.

In [31]:
for index,e in ratings.head().iterrows():
    print ("index: ", e['userId'], e['movieId'], e['rating'], e['timestamp'])

index:  1.0 16.0 4.0 1217897793.0
index:  1.0 24.0 1.5 1217895807.0
index:  1.0 32.0 4.0 1217896246.0
index:  1.0 47.0 4.0 1217896556.0
index:  1.0 50.0 4.0 1217896523.0


**```itertuples()```** 함수는 인덱스 순서대로 데이터를 조회하게 된다.

In [32]:
for e in ratings.head().itertuples():
    print (e[0], e[1], e[2], e[3], e[4])

0 1 16 4.0 1217897793
1 1 24 1.5 1217895807
2 1 32 4.0 1217896246
3 1 47 4.0 1217896556
4 1 50 4.0 1217896523


### S.6.4 missing values

결측 값이 있는 경우, 평균을 구하거나 통계분석에 있어 문제가 될 수 있다.
isnull() 함수는 결측 값인지 true, false를 반환한다.
결측 값인지 아닌지 반환 값을 sum()하게 되면 결측 개수를 알 수 있다.

In [33]:
ratings.isnull().sum()

userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

unique()는 중복을 제거하고 유일한 값을 출력한다.
pandas의 DataFrame.shape은 차원을 출력하는데, 사용자는 668개, 영화는 10,325개를 가지고 있다.
사용자의 최대값과는 동일하지만, 영화는 사용자의 평점이 존재하지 않는 경우도 많아 최대 값과 149,352와 차이가 있다.

In [34]:
nUsers=ratings.userId.unique().shape[0]
nItems=ratings.movieId.unique().shape[0]

print ("Users \tN={}\tMax={}".format(nUsers, max(ratings.userId)))
print ("Movies \tN={}\tMax={}".format(nItems, max(ratings.movieId)))

Users 	N=668	Max=668
Movies 	N=10325	Max=149532


### S.6.5 ratings와 movies 데이터 합치기

```merge()```는 공통 속성 ```on```을 기준으로 dataframe을 병합한다.
```how```는 ```left, right, inner, outer``` 4가지 방법으로 병합할 수 있다.
* ```left```: 왼쪽 dataframe의 모든 행을 보존
* ```right```: 오른쪽 dataframe의 모든 행을 보존
* ```inner```: 기본 **```default```** 왼쪽 오른쪽 dataframe의 공통 값으로만 병합
* ```outer```: 왼쪽 오른쪽 dataframe의........ 행의 일치하는 값이 없는 경우 NaN


영화와 사용자평점에는 movieId라는 공통 속성이 있고, 이를 기준으로 두 파일을 합쳐보자.
how='left'이므로, 왼쪽인 ratings의 모든 속성을 보존하고, 영화정보를 병합한다.

In [35]:
ratingsMovie=pd.merge(ratings, movies, on='movieId', how='left')
ratingsMovie.head(10)

userId  movieId  rating   timestamp  \
0       1       16     4.0  1217897793   
1       1       24     1.5  1217895807   
2       1       32     4.0  1217896246   
3       1       47     4.0  1217896556   
4       1       50     4.0  1217896523   
5       1      110     4.0  1217896150   
6       1      150     3.0  1217895940   
7       1      161     4.0  1217897864   
8       1      165     3.0  1217897135   
9       1      204     0.5  1217895786   

                                       title                   genres  
0                              Casino (1995)              Crime|Drama  
1                              Powder (1995)             Drama|Sci-Fi  
2  Twelve Monkeys (a.k.a. 12 Monkeys) (1995)  Mystery|Sci-Fi|Thriller  
3                Seven (a.k.a. Se7en) (1995)         Mystery|Thriller  
4                 Usual Suspects, The (1995)   Crime|Mystery|Thriller  
5                          Braveheart (1995)         Action|Drama|War  
6                           Apollo 13 (1995)     Adventure|Drama|IMAX  
7                        Crimson Tide (1995)       Drama|Thriller|War  
8          Die Hard: With a Vengeance (1995)    Action|Crime|Thriller  
9       Under Siege 2: Dark Territory (1995)                   Action

## S.7 인지도 기반 추천

인지도 기반 추천은 사람들이 높은 평점을 준 영화를 추천하는 방식을 말한다.
* 우선 영화의 평균 평점을 계산하고,
* 다음으로 그 가운데 높은 평점을 추천한다.

### 평균 평점 계산

groupby('title')는 영화제목별로 구분해서, 사용자 평점 mean() 평균을 구한다.

In [36]:
ratingsByTitle=pd.DataFrame(ratingsMovie.groupby('title')['rating'].mean())

### 정렬

평점이 높은 순으로 정렬해보자.
sort() 함수는 Pandas 0.20 버전 (2017-05-05) 이후 제거 되었고, sort_values()를 사용하면 된다.
sort_values() 함수에는 정렬할 컬럼명 'rating'과 내림차순, 오름차순을 정해준다.

In [37]:
ratingsByTitle.sort_values('rating', ascending=False).head(10)

rating
title                                                     
Saddest Music in the World, The (2003)                 5.0
Interstate 60 (2002)                                   5.0
Gunfighter, The (1950)                                 5.0
Heima (2007)                                           5.0
Limelight (1952)                                       5.0
Plague Dogs, The (1982)                                5.0
Love Me If You Dare (Jeux d'enfants) (2003)            5.0
Syrup (2013)                                           5.0
Interstella 5555: The 5tory of the 5ecret 5tar ...     5.0
Symbol (Shinboru) (2009)                               5.0

### Utility matrix

사용자 m, 상품 n이 있다고 하자. 
m x n 테이블이 만들어 지고, 그 셀에는 사용자의 항목에 대한 의견이 입력된다.


사용자 A는 영화 m2, m4에 대해 1점 4점 평점을 부여하였다.
평점은 5점 만점으로 3점은 보통, 1점은 부정적, 5점은 긍정적이다.

사용자 \ 영화 | m1 | m2 | m3 | m4 | m5
-----|-----|-----|-----|-----|-----
A | - | 1 | - | 4 | -
B | - | 4 | - | 2 | 3
C | - | 1 | - | 4 | 4

문제는 이 테이블에 빈 값이 많을 수 밖에 없다는 것이다. 이를 해결하는 방법은:
* 사용자로 하여금 모든 영화에 평점을 부여하도록 하거나
* 평점을 유추하는 것이다.

#### 사용자, 영화별 평점배열 생성

사용자 x 영화 배열을 새로이 생성하고, 각 셀을 해당하는 평점으로 채워줄 수 있다.
이 경우, 앞서 보았듯이 사용자ID는 일련번호로 비어 있는 값이 없으나, 영화ID는 듬성듬성 비어 있는 값이 많다.
numpy array을 가능한 최대의 값으로 shape을 정해서 갯수를 정해 주어야 한다.
그러나, 이 방법보다는 Pandas에서 지원하는 pivot_table() 함수를 사용하면 보다 쉽게 만들어 줄 수 있다.

피벗테이블 ```pivot_table```은 데이터를 그룹별로 구분하여 각 그룹의 갯수, 합계, 평균 등을 분석하는 방법이다.
영화의 사용자별, 영화별로 평점을 계산해 보자.
ratings를 ```pivot()``` 해보자. pivot은 행을 열로, 또는 열을 행으로 전환하여 데이터를 그룹핑해서 평균, 합계를 계산해준다.
* index에는 행이 되는 변수명으로, 'userId'를 적어준다. 
* columns는 열이 되는 값으로 'movidId'를 적어준다.
* values는 셀에 입력되는 값으로 'rating'의 평균을 출력한다.

fillna(0)는 NA값을 0으로 대체하게 된다.

**```pivot_table()```**은 셀에 **복수**의 값이 허용되고 (```pivot()```은 복수의 값이 허용되지 않는다), 그런 경우 ```numpy.mean()``` 평균 값을 **기본 default**로 채택한다.

In [38]:
utility = ratingsMovie.pivot_table(index='userId', columns='title', values='rating')

In [76]:
utility['Casino (1995)'][0:10]

userId
1     4.0
2     NaN
3     NaN
4     NaN
5     NaN
6     NaN
7     NaN
8     NaN
9     4.0
10    NaN
Name: Casino (1995), dtype: float64

In [77]:
utility.head()

title   '71 (2014)  'Hellboy': The Seeds of Creation (2004)  \
userId                                                        
1              NaN                                      NaN   
2              NaN                                      NaN   
3              NaN                                      NaN   
4              NaN                                      NaN   
5              NaN                                      NaN   

title   'Round Midnight (1986)  'Til There Was You (1997)  'burbs, The (1989)  \
userId                                                                          
1                          NaN                        NaN                 NaN   
2                          NaN                        NaN                 NaN   
3                          NaN                        NaN                 NaN   
4                          NaN                        NaN                 NaN   
5                          NaN                        NaN                 NaN   

title   'night Mother (1986)  (500) Days of Summer (2009)  \
userId                                                      
1                        NaN                          NaN   
2                        NaN                          NaN   
3                        NaN                          NaN   
4                        NaN                          NaN   
5                        NaN                          NaN   

title   *batteries not included (1987)  ...And Justice for All (1979)  \
userId                                                                  
1                                  NaN                            NaN   
2                                  NaN                            NaN   
3                                  NaN                            NaN   
4                                  NaN                            NaN   
5                                  NaN                            NaN   

title   10 (1979)  ...  [REC] (2007)  [REC]² (2009)  [REC]³ 3 Génesis (2012)  \
userId             ...                                                         
1             NaN  ...           NaN            NaN                      NaN   
2             NaN  ...           NaN            NaN                      NaN   
3             NaN  ...           NaN            NaN                      NaN   
4             NaN  ...           NaN            NaN                      NaN   
5             NaN  ...           NaN            NaN                      NaN   

title   a/k/a Tommy Chong (2005)  eXistenZ (1999)  \
userId                                              
1                            NaN              NaN   
2                            NaN              NaN   
3                            NaN              NaN   
4                            NaN              NaN   
5                            NaN              NaN   

title   loudQUIETloud: A Film About the Pixies (2006)  xXx (2002)  \
userId                                                              
1                                                 NaN         NaN   
2                                                 NaN         NaN   
3                                                 NaN         NaN   
4                                                 NaN         NaN   
5                                                 NaN         NaN   

title   xXx: State of the Union (2005)  ¡Three Amigos! (1986)  \
userId                                                          
1                                  NaN                    NaN   
2                                  NaN                    NaN   
3                                  NaN                    NaN   
4                                  NaN                    NaN   
5                                  NaN                    NaN   

title   À nous la liberté (Freedom for Us) (1931)  
userId                                             
1                                             NaN  
2                    

### 상관관계

corrwith() 함수는 행이나 컬럼끼리 상관관계를 계산한다. 
'Toy Story (1995)'와 상관관계를 계산해 보자.
상관관계를 계산하면서 RuntimeWarning: divide by zero가 발생할 수 있는데 이는 결측값 NaN이 남아 있어서 그렇다.

astype()으로 평점을 소수로 형변환해주면 그런 Warning이 사라진다.

앞서 fillna()로 결측값을 제거했다.

In [79]:
corrToyStory = pd.DataFrame(utility.corrwith(utility['Toy Story (1995)']), columns=['corr'])
corrToyStory.dropna(inplace=True)
corrToyStory.head()

/home/jsl/.local/lib/python3.6/site-packages/numpy/lib/function_base.py:2551: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar)
/home/jsl/.local/lib/python3.6/site-packages/numpy/lib/function_base.py:2480: RuntimeWarning: divide by zero encountered in true_divide
  c *= np.true_divide(1, fact)


corr
title                                   
'burbs, The (1989)              0.470402
(500) Days of Summer (2009)     0.301871
*batteries not included (1987) -0.058926
...And Justice for All (1979)  -0.046829
10 (1979)                       0.000000

In [80]:
corrToyStory.sort_values('corr', ascending=False).head()

corr
title                                           
Two Mules for Sister Sara (1970)             1.0
Raven, The (1963)                            1.0
Alice (2009)                                 1.0
Assassination of Richard Nixon, The (2004)   1.0
Unvanquished, The (Aparajito) (1957)         1.0

### 평가건수

평가를 몇 건이나 받았는지 세어보자.
앞서 만든 ratingsMovie의 'title'별 'rating'의 건수를 세어보자.

In [81]:
countRatings = ratingsMovie.groupby('title')['rating'].count().to_frame('count')
countRatings.sort_values(by='count', ascending=False).head()

count
title                                  
Pulp Fiction (1994)                 325
Forrest Gump (1994)                 311
Shawshank Redemption, The (1994)    308
Jurassic Park (1993)                294
Silence of the Lambs, The (1991)    290

### merge


In [82]:
corrCountToyStory=pd.merge(corrToyStory, countRatings, on='title', how='left')

정렬을 2개할 경우에는 ['corr', 'count']와 같이 배열을 만들어서 넣어준다.

In [47]:
corrCountToyStory.sort_values(['corr', 'count'], ascending=[False, False]).head()

corr  count
title                                                          
Toy Story (1995)                                     1.0    232
Eve's Bayou (1997)                                   1.0     10
Nightmare on Elm Street 3: Dream Warriors, A (1...   1.0      9
Wild Strawberries (Smultronstället) (1957)           1.0      9
88 Minutes (2008)                                    1.0      7

column 명을 변경한다.

In [29]:
corr_rcountToyStory.columns=['corr','ratingsCount']

In [40]:
corr_rcountToyStory.head(10)

corr  ratingsCount
title                                                                     
'burbs, The (1989)                                  0.470402            20
(500) Days of Summer (2009)                         0.301871            37
*batteries not included (1987)                     -0.058926            11
...And Justice for All (1979)                      -0.046829            10
10 (1979)                                           0.000000             3
10 Things I Hate About You (1999)                   0.349920            59
10,000 BC (2008)                                    0.155556            11
101 Dalmatians (1996)                               0.161703            42
101 Dalmatians (One Hundred and One Dalmatians)...  0.439606            37
102 Dalmatians (2000)                              -0.519589             7

In [41]:
corr_rcountToyStory.sort('ratingsCount', ascending=False).head(10)

corr  ratingsCount
title                                                            
Pulp Fiction (1994)                        0.154139           325
Forrest Gump (1994)                        0.092166           311
Shawshank Redemption, The (1994)           0.118852           308
Jurassic Park (1993)                       0.417862           294
Silence of the Lambs, The (1991)           0.071004           290
Star Wars: Episode IV - A New Hope (1977)  0.148712           273
Matrix, The (1999)                         0.254059           261
Terminator 2: Judgment Day (1991)          0.257904           253
Schindler's List (1993)                    0.313121           248
Braveheart (1995)                          0.183313           248

#### filtering

```[corr_rcountToyStory ['ratingsCount']>50]```는 컬럼명에 대한 조건을 넣어 데이터를 필터링을 할 수 있다.

In [47]:
corr_rcountToyStory[corr_rcountToyStory ['ratingsCount']>50].sort('corr', ascending=False).head()

corr  ratingsCount
title                                                         
Toy Story (1995)                        1.000000           232
Wallace & Gromit: A Close Shave (1995)  0.725063            55
Toy Story 2 (1999)                      0.709677           104
Client, The (1994)                      0.695989            65
Others, The (2001)                      0.681520            53

pandas Dataframe을 numpy array로 변환하려면 단순히 ```values```해주면 된다.

## S.8 경사도 하강 Matrix Factorization

경사도 하강법으로 매트릭스를 분할해서 추천 문제를 풀어보자.

### S.8.1 알고리즘

#### 단계 1: p와 q를 초기화 한다.

원래 평점행렬을 분해하여 p, q를 구하려고 한다. 우선 p와 q를 임의의 값으로 초기화 하자.
* p는 $i \times k$ 사용자 벡터 ($i$는 사용자, $k$는 latent features의 갯수를 말한다.)
* q는 $k \times j$ 상품 벡터  ($j$는 상품, $k$는 latent features의 갯수)

#### 단계 2: 예측 값 계산

행렬을 분해하고 얻게 되는 p, q를 곱하게 되면 r의 예측 값을 계산할 수 있다.
물론 이 값은 첫 반복에는 만족스럽지 못할 것이고 반복을 통해 최적값에 접근하게 된다.
* $\hat{r}$은 $\hat{r}_{ij}$는 p와 q의 곱셈 연산으로 계산한다. ($\hat{r}$은 평점 **예측** 값)
* $\hat{r}_{ij} = \sum_{k=1}^K p_{ik} q_{kj}$

#### 단계 3: 오류 계산

예측 값과 실제 값의 차이가 오류가 되고, 이를 계산한다.
* 예측 값의 차이는 SE Squared Error로 다음과 같이 계산된다.
    * $e_{ij} = (r_{ij} - \hat{r_{ij}})^2 = (r_{ij} - \sum_{k=1}^K p_{ik} q_{kj})^2$

* 또는 overfitting을 피하기 위해, SE에 Regularization 식을 더해 계산할 수도 있다. $\beta$는 regularization 계수이다.
    * $e_{ij}=(r_{ij} - \sum_{k=1}^K p_{ik} q_{kj})^2 + \frac{1}{2}\beta \sum_{k=1}^K (||p||^2 + ||q||^2)$


#### 단계 4: 경사도 계산

오류를 최소화하기 위해서는 경사도를 찾아 갱신해야 한다. 위 MSE 오류식을 p, q에 대해 편미분해서 경사도를 찾는다.
오류 regularization을 사용하려면, 그 계산식을 편미분해야 한다.
이를 **경사도하강법 Gradient Descent**이라고 한다.

* $\frac{\partial e}{\partial{p_j}} = 2 \times (r_{ij} - \sum_{k=1}^K p_{ik} q_{kj}) \times -q_{kj}$
* $\frac{\partial e}{\partial{q_j}} = 2 \times (r_{ij} - \sum_{k=1}^K p_{ik} q_{kj}) \times -p_{kj}$

#### 단계 5: Update rules

실제 - 예측의 차이는 오류이다. 그 오류에 학습비율 $\alpha$을 곱해서 갱신한다. 
$\alpha$ 값이 너무 크게 되면 오류의 최저점을 통과할 수 있게 되고, 너무 작게 되면 최저점을 찾는 횟수가 늘어날 수 밖에 없다.
반복이 거듭되면 오류가 차즘 줄어들고, 어떤 값에 수렴하게 된다.

* $p_{new} = p_{old} - \alpha \times 2 \times (r - \sum_{k=1}^K p_{ik} q_{jk}) \times -q = p_{old} + 2 \alpha q (r - \sum_{k=1}^K p_{ik} q_{jk})$
* $q_{new} = q_{old} - \alpha \times 2 \times (r - \sum_{k=1}^K p_{ik} q_{jk}) \times -p = q_{old} + 2 \alpha p (r - \sum_{k=1}^K p_{ik} q_{jk})$

### S.8.2 풀어보기

```python
[5,2,0,4,3],
[3,1,2,4,0],
[2,0,1,4,0],
[2,0,4,3,5],
[4,0,5,4,0],
```

#### 단계 1: 초기화

P, Q를 1로 초기화하자. 무작위 값으로 초기화할 수 있지만, 손계산이 어려워지게 된다.

```python
1   1
1   1     1   1   1   1   1
1   1     1   1   1   1   1
1   1
1   1
```

#### 단계 2: 예측 값

예측 $\hat{r}_{ij} = \sum_{k=1}^K p_{ik} q_{kj}$은 dot 연산으로 계산된다.
p(m,k), q(k,n)를 dot연산하면 (m,n) 결과가 된다.

연산과정을 보여주기 위해 $p_{11}$을 p로 놓고,
* $\hat{r}_{1j}$를 계산하면, $p \times 1 + 1 \times 1 = p + 1$가 된다. 첫 행에 5개의 결과가 계산된다.
* $\hat{r}_{2j}$를 계산하면, $1 \times 1 + 1 \times 1 = 1 + 1 = 2$가 된다. 둘째 행에 5개의 결과가 계산된다.
* 3회 더 반복을 하자.

```python
p   1                           p+1 p+1 p+1 p+1 p+1
1   1     1   1   1   1   1     2   2   2   2   2
1   1     1   1   1   1   1     2   2   2   2   2
1   1                           2   2   2   2   2
1   1                           2   2   2   2   2
```

#### 단계 3: 오류 계산

제곱오류 Squared Error를 계산하면:

$(5-(p+1))^2+(2-(p+1))^2+(0-(p+1))^2+(4-(p+1))^2+(3-(p+1))^2$

#### 단계 4: 경사하강법

편미분하면:

$\frac{\partial e}{\partial{p}} = -2 ((4-p)+(1-p)+(-1-p)+(3-p)+(2-p)) = -2(9-5p) = -18 + 10p$

이를 0으로 놓으면 p=1.8

#### 단계 5: update

앞서 계산한 p=1.8로 대체하면, $p_{new} = p_{old} + \alpha \times gradient = 1 + 1 \times 1.8 = 2.8$
손계산이 편하도록 $\alpha$는 1로 계산하자.

```python
1.8 1                           2.8 2.8 2.8 2.8 2.8
1   1     1   1   1   1   1     2   2   2   2   2
1   1     1   1   1   1   1     2   2   2   2   2
1   1                           2   2   2   2   2
1   1                           2   2   2   2   2
```

#### 단계 2 반복: 예측 값 계산

이번에는 q에 대해서 경사도를 구해서 예측을 계산해보자.
앞서 **p는 행으로 계산**하였지만 이번에는 **컬럼**으로 값을 구하기 위해, ```dot()``` 계산을 하면:

```python
1.8 1                           1.8q+1 2.8 2.8 2.8 2.8
1   1     q   1   1   1   1     q+1    2   2   2   2
1   1     1   1   1   1   1     q+1    2   2   2   2
1   1                           q+1    2   2   2   2
1   1                           q+1    2   2   2   2
```

#### 단계 3 반복: 오류 계산

**R의 첫 컬럼**을 읽어서 계산한다.

$(5-(1.8q+1))^2+(3-(q+1))^2+(2-(q+1))^2+(2-(q+1))^2+(4-(q+1))^2$

#### 단계 4 반복: 경사하강법

$\frac{\partial e}{\partial{q}} = -2 (1.8(4-1.8q)+(2-q)+(1-q)+(1-q)+(3-q)) = -2(14.2-7.24p) = -28.4 + 14.48p$
이를 0으로 놓으면 q=1.9613

#### 단계 5 반복: update

앞서 계산한 q=1.961로 대체하면:

```python
1.8 1                           3.530  2.8 2.8 2.8 2.8
1   1     1.961 1   1   1   1   2.961  2   2   2   2
1   1     1     1   1   1   1   2.961  2   2   2   2
1   1                           2.961  2   2   2   2
1   1                           2.961  2   2   2   2
```

지금까지는 1회 반복을 한 것이다. 이상과 같은 식으로 오류가 최소화될 때까지 반복을 거듭하게 된다.

### S.8.3 프로그램으로 풀어보기

R은 실제 값을 가지고 있는 배열이다.
0은 결측에 해당하는 경우에 넣은 값이다.

In [23]:
import numpy as np
R = np.array([
     [5,2,0,4,3],
     [3,1,2,4,0],
     [2,0,1,4,0],
     [2,0,4,3,5],
     [4,0,5,4,0],
    ])

R의 행과 열의 개수를 ```shape``` 명령어로 구할 수 있다.

In [24]:
row=R.shape[0]
col=R.shape[1]
row,col

(5, 5)

계산을 위해 필요한 계수의 값을 정하자.
* K는 숨겨진 특징으로 P의 열, Q의 행에 해당한다.
* $\alpha$는 학습율
* $\beta$는 regularization 계수

In [25]:
K = 2
alpha=0.0002
beta=0.02

#### 단계 1: P, Q 초기화

P, Q에 어떤 값으로든 입력하여 초기화해야 하는데, 무작위 숫자를 채워 넣어보자.

In [26]:
#P=np.ones([row,K])
#Q=np.ones([col,K])
P=np.random.rand(row,K)
Q=np.random.rand(col,K)

In [27]:
print ("P\n{}\n\nQ\n{}".format(P, Q))

P
[[0.67720745 0.736777  ]
 [0.32545556 0.44371672]
 [0.43369265 0.37241648]
 [0.61006745 0.30984679]
 [0.14176938 0.51665362]]

Q
[[0.59630065 0.7902821 ]
 [0.95328006 0.84825301]
 [0.41509567 0.02188665]
 [0.6639103  0.578908  ]
 [0.81081996 0.529222  ]]


P, Q의 shape은 서로 같다. dot연산을 하기 위해 Q.T를 사용하자.

In [28]:
P.shape, Q.shape, Q.T.shape

((5, 2), (5, 2), (2, 5))

P의 첫째 행을 읽어보자. 프로그래밍에서 반복을 하게 되면, P와 Q를 이렇게 하나씩 선택하여 계산하게 된다.

In [29]:
P[0,:]

array([0.67720745, 0.736777  ])

Q.T의 첫 컬럼을 읽어보자.

In [30]:
Q.T[:,0]

array([0.59630065, 0.7902821 ])

#### 단계 2: 예측

rating의 예측 값은 $m \times n$ 행렬이어야 한다. P(m,k)와 Q.T(k,n)로 연산을 해야 그와 같은 행렬이 만들어진다.

우선 첫 번째 **```R[0,0]```**의 예측 값을 계산해 보자. 
R의 예측 값은 PQ의 dot으로 계산된다.
실제와 예측의 차이는 오류가 되고, 이 오류는 아직 큰 차이가 있고, 반복을 하면서 근사 값으로 갱신되게 된다.

In [ ]:
rhat=np.dot(P[0,:],Q.T[:,0]) #2 when P=Q=1
#np.dot(P[0,:],Q.T) #[2., 2., 2., 2., 2.] when P=Q=1

In [31]:
print ("R[0,0]: actual={} predicted={:.3f}".format(R[0,0], rhat))

R[0,0]: actual=5 predicted=0.986


#### 단계 3: 오류

오류는 실제와 예측의 차이이다.

In [ ]:
eij=R[0,0]-rhat #3 when P=Q=1
#e0=R[0,:]-rhat #[ 3.,  0., -2.,  2.,  1.] when P=Q=1

In [32]:
print ("Error={:.3f}".format(eij))

Error=4.014


#### 단계 4: 경사도 하강법

P의 경사도 하강법으로 p를 계산해보자.

$\frac{\partial e}{\partial{p_j}} = 2 \times (r_{ij} - \sum_{k=1}^K p_{ik} q_{kj}) \times -q_{kj}$


In [33]:
#eij*Q[0][0]
np.dot(eij,Q[0][0])

2.393502573639733

In [34]:
beta*P[0][0]

0.013544148986175187

In [35]:
for k in range(K):
    #pGradient=2*np.dot(eij,Q[k][0]) - beta*P[0][k] #regularization
    pGradient=2*np.dot(eij,Q[k][0]) # no regularization
    print ("k: {} pGradient: {}".format(k, pGradient))

k: 0 pGradient: 4.787005147279466
k: 1 pGradient: 7.652778023285386


이번에는 Q gradient를 계산해 보자.

In [36]:
#eij*P[0][0]
np.dot(eij.T,P[0][0])

2.7182559021324995

In [37]:
beta*Q[0][0]

0.011926013084617262

In [38]:
for k in range(K):
    #qGradient=2*np.dot(eij,Q[k][0]) - beta*Q[k][0] # regularization
    qGradient=2*np.dot(eij,Q[k][0]) # no regularization
    print ("k: {} qGradient: {}".format(k, qGradient))

k: 0 qGradient: 4.787005147279466
k: 1 qGradient: 7.652778023285386


#### 단계 5: update

이제 P, Q를 갱신해보자.

In [39]:
alpha

0.0002

In [40]:
for k in range(K):  
    #pGradient=2*np.dot(eij,Q[k][0]) - beta*P[0][k] # regularization
    pGradient=2*np.dot(eij,Q[k][0]) # no regularization
    P[0][k]+=alpha*pGradient
    print (P[0][k], end=" ")

0.6781648503382152 0.7383075561941077 

P의 첫 행이 갱신된다.

In [41]:
print (P)

[[0.67816485 0.73830756]
 [0.32545556 0.44371672]
 [0.43369265 0.37241648]
 [0.61006745 0.30984679]
 [0.14176938 0.51665362]]


In [50]:
for k in range(K):  
    #qGradient=2*np.dot(eij,P[0][k]) - beta*Q.T[k][0] # regularization
    qGradient=2*np.dot(eij,P[0][k]) # no regularization
    Q.T[k][0]+=alpha*qGradient
    print (Q[k][0], end=" ")

0.6060858205588044 0.9532800574827203 

#### R은 P x Q로 계산

행렬을 분해해서 P, Q를 갱신한 값을 서로 곱하면 원래의 행렬이 복원된다.
이 값은 예측 값으로 원행렬과의 차이만큼 오류가 된다.
물론 첫 반복에는 오류가 크겠지만 반복을 할수록 경사도가 하강하면서 그 값은 줄어들게 된다.

이제 1회 반복을 수행하였다.
이제 P, Q 행열의 각 요소에 대해 경사도하강법을 적용하고, 이를 적당한 횟수만큼 반복을 해보자.
전체 행렬 P ($5 \times 2$), Q ($2 \times 5$)의 ```dot()``` 연산을 하면 $5 \times 5$ 벡터가 계산된다.

In [52]:
print ("R:\n{}".format(np.round(np.dot(P,Q.T),1)))

R:
[[1.  1.3 0.3 0.9 0.9]
 [0.6 0.7 0.1 0.5 0.5]
 [0.6 0.7 0.2 0.5 0.5]
 [0.6 0.8 0.3 0.6 0.7]
 [0.5 0.6 0.1 0.4 0.4]]


#### 반복해서 P, Q 갱신

그러면 반복을 함수로 해보자.
* regularization을 적용하고, 하지 않는 경우를 별도로 계산해보자.
* P, Q를 1로 초기화를 한 경우, P의 두 컬럼이 동일하게 계산된다. Q도 마찬가지이다.
* 오류는 **정확한 오류를 계산하지 않고** 있다. 결측에 0을 초기화한 후 계산을 해서 예측을 구하고, (실제-예측)의 계산을 한다면 애매하다. 예들 들어, 예측이 5라면 오류가 크고, 예측이 1이라면 보다 정확하다고 할 수 없다. 다만, 여기서는 **줄어드는 추세를 보면서 alpha, 반복횟수를 조정**하자. 

In [74]:
#def gradientDescentMF(R, P, Q, K, alpha, beta, iters):
def gradientDescentMF(R, K, alpha, beta, iters):
    """
    in:
        R: m x n array
        P: m x k
        Q: n x k, so to be transposed to Q.T
        K: k latent features
        alpha: learning rate
        beta: regularization rate
        iters: n of iterations
    out: P, Q
    """
    import numpy as np
    row=R.shape[0]
    col=R.shape[1]
    P=np.random.rand(row,K)
    Q=np.random.rand(col,K)
    #P=np.ones([row,K]) # P=1 produces Pm0=Pm1
    #Q=np.ones([col,K]) # Q=1 produces Qm0=Qm1
    for iter in range(iters):
        cost=0
        for i in range(row):
            for j in range(col):
                if R[i][j] > 0:  # equality is out because R was set to 0 for missing values 
                    rhat=np.dot(P[i,:],Q.T[:,j])
                    eij=R[i,j]-rhat #R[i][j]-rhat
                    cost+=np.power(eij, 2)  #??cost all add up with nested for?
                    for k in range(K):
                        pGradient=2*np.dot(eij,Q.T[k][j]) - beta*P[i][k] #regularization
                        #pGradient=2*eij*Q.T[k][j] - beta*P[i][k] #regularization
                        #pGradient=2*np.dot(eij,Q.T[k][j])         #no regularization
                        qGradient=2*np.dot(eij,P[i][k]) - beta*Q.T[k][j] #regularization
                        #qGradient=2*eij*P[i][k] - beta*Q.T[k][j] #regularization
                        #qGradient=2*np.dot(eij,P[i][k])           #no regularization
                        P[i][k]+=alpha*pGradient
                        Q.T[k][j]+=alpha*qGradient
        if iter%1000==0:
            print ("iter:{:5d}\tCost {:.5f}\nP {}\n Q {} ".format(iter, cost, P, Q))
    return P, Q

함수를 호출하기 위해 설정을 다시 한다.
오류가 최소화되는 지점이 넘어서 지나가지 않도록 **alpha**를 조정하고,
**반복회수**도 최소오류에 수렴하도록 조정해준다.

In [83]:
iters=11001
K = 2
alpha=0.00006
beta=0.02 #regularization

In [84]:
R

array([[5, 2, 0, 4, 3],
       [3, 1, 2, 4, 0],
       [2, 0, 1, 4, 0],
       [2, 0, 4, 3, 5],
       [4, 0, 5, 4, 0]])

1000회마다 출력하고 있고, cost가 점차로 줄어들고 있는 것을 볼 수 있다.
**alpha와 반복회수를 조정해가면서 cost를 최소화**해보자. 또는 **regularization**을 조정하기도 해보자.

In [85]:
P, Q=gradientDescentMF(R, K, alpha, beta, iters)

iter:    0	Cost 167.68797
P [[0.67965096 0.81734641]
 [0.2326622  0.14399489]
 [0.47553262 0.02912597]
 [0.44118706 0.85553561]
 [0.69232085 0.79637602]]
 Q [[0.08404926 0.26079645]
 [0.75058074 0.68219818]
 [0.06849449 0.64100695]
 [0.72990564 0.11404837]
 [0.67555893 0.69846348]] 
iter: 1000	Cost 24.91024
P [[1.29064164 1.36043429]
 [0.8729947  0.69870821]
 [0.98457291 0.3770479 ]
 [1.00346788 1.54938322]
 [1.24641258 1.50268553]]
 Q [[1.01769359 1.1878098 ]
 [0.80196094 0.73552498]
 [0.72719132 1.44657336]
 [1.67535359 0.96512428]
 [1.04310744 1.24928481]] 
iter: 2000	Cost 11.02725
P [[1.4101313  1.48808116]
 [1.17154892 0.87527805]
 [1.24654739 0.44136771]
 [0.97368821 1.6500451 ]
 [1.36233709 1.75113324]]
 Q [[1.24705789 1.31975476]
 [0.73492291 0.67906418]
 [0.8596861  1.72207701]
 [1.92201375 1.01646516]
 [1.15057922 1.47083517]] 
iter: 3000	Cost 9.01942
P [[1.41695247 1.48473304]
 [1.28870966 0.84723061]
 [1.37157766 0.35635855]
 [0.87729493 1.69210448]
 [1.32420047 1.83761722]

In [86]:
print ("P\n{}\n\nQ\n{}".format(P, Q))

P
[[ 1.67539754  1.17665455]
 [ 1.5225777   0.54493168]
 [ 1.56357774 -0.02165909]
 [ 0.52021302  2.01656359]
 [ 1.14239015  2.16979143]]

Q
[[1.69783336 0.92470731]
 [0.56563679 0.70790128]
 [0.61378612 1.92263701]
 [2.27839377 0.68015784]
 [0.56695542 2.10396887]]


#### R

R의 실제 값은 아래와 같다. P, Q를 곱해서 얻은 예측과 비교해보자. 0은 새로 값으로 채워졌고, 기존 존재했던 값은 다소 차이가 발생하기도 한다.
```python
 [5,2,0,4,3],
 [3,1,2,4,0],
 [2,0,1,4,0],
 [2,0,4,3,5],
 [4,0,5,4,0],
```

In [87]:
print ("R:\n{}".format(np.round(np.dot(P,Q.T),0)))

R:
[[4. 2. 3. 5. 3.]
 [3. 1. 2. 4. 2.]
 [3. 1. 1. 4. 1.]
 [3. 2. 4. 3. 5.]
 [4. 2. 5. 4. 5.]]


### S.8.4 Spark

Scikit-learn은 추천 라이브러리를 제공하고 있지 않는다.
Spark는 ALS를 사용하여 추천 문제를 풀고 있다.

#### utility matrix를 변환

In [128]:
import numpy as np
R = np.array([
     [5,3,0,1],
     [4,0,0,1],
     [1,1,0,5],
     [1,0,0,4],
     [0,1,5,4],
    ])

In [129]:
R = np.array([
     [5,2,0,4,3],
     [3,1,2,4,0],
     [2,0,1,4,0],
     [2,0,4,3,5],
     [4,0,5,4,0],
    ])

In [130]:
row=R.shape[0]
col=R.shape[1]
ratingsUI=np.zeros([row*col,3])

In [133]:
counter=0
for r in range(row):
    for c in range(col):
        ratingsUI[counter]=[r,c,R[r,c]]
        print ("r:{0} c:{1} ratings:{2} Rij:{3}".format(r,c,ratingsUI[counter],R[r,c]))
        counter+=1

r:0 c:0 ratings:[0. 0. 5.] Rij:5
r:0 c:1 ratings:[0. 1. 2.] Rij:2
r:0 c:2 ratings:[0. 2. 0.] Rij:0
r:0 c:3 ratings:[0. 3. 4.] Rij:4
r:0 c:4 ratings:[0. 4. 3.] Rij:3
r:1 c:0 ratings:[1. 0. 3.] Rij:3
r:1 c:1 ratings:[1. 1. 1.] Rij:1
r:1 c:2 ratings:[1. 2. 2.] Rij:2
r:1 c:3 ratings:[1. 3. 4.] Rij:4
r:1 c:4 ratings:[1. 4. 0.] Rij:0
r:2 c:0 ratings:[2. 0. 2.] Rij:2
r:2 c:1 ratings:[2. 1. 0.] Rij:0
r:2 c:2 ratings:[2. 2. 1.] Rij:1
r:2 c:3 ratings:[2. 3. 4.] Rij:4
r:2 c:4 ratings:[2. 4. 0.] Rij:0
r:3 c:0 ratings:[3. 0. 2.] Rij:2
r:3 c:1 ratings:[3. 1. 0.] Rij:0
r:3 c:2 ratings:[3. 2. 4.] Rij:4
r:3 c:3 ratings:[3. 3. 3.] Rij:3
r:3 c:4 ratings:[3. 4. 5.] Rij:5
r:4 c:0 ratings:[4. 0. 4.] Rij:4
r:4 c:1 ratings:[4. 1. 0.] Rij:0
r:4 c:2 ratings:[4. 2. 5.] Rij:5
r:4 c:3 ratings:[4. 3. 4.] Rij:4
r:4 c:4 ratings:[4. 4. 0.] Rij:0


In [134]:
ratingsUI

array([[0., 0., 5.],
       [0., 1., 2.],
       [0., 2., 0.],
       [0., 3., 4.],
       [0., 4., 3.],
       [1., 0., 3.],
       [1., 1., 1.],
       [1., 2., 2.],
       [1., 3., 4.],
       [1., 4., 0.],
       [2., 0., 2.],
       [2., 1., 0.],
       [2., 2., 1.],
       [2., 3., 4.],
       [2., 4., 0.],
       [3., 0., 2.],
       [3., 1., 0.],
       [3., 2., 4.],
       [3., 3., 3.],
       [3., 4., 5.],
       [4., 0., 4.],
       [4., 1., 0.],
       [4., 2., 5.],
       [4., 3., 4.],
       [4., 4., 0.]])

#### DataFrame

pandas를 경유해서 dataframe으로 변환한다.

In [135]:
import pandas as pd
pdf = pd.DataFrame(ratingsUI)

In [137]:
import os
os.environ["PYSPARK_PYTHON"]="/usr/bin/python3"
os.environ["PYSPARK_DRIVER_PYTHON"]="/usr/bin/python3"

In [138]:
import pyspark

myConf=pyspark.SparkConf()
spark = pyspark.sql.SparkSession.builder\
    .master("local")\
    .appName("myApp")\
    .config(conf=myConf)\
    .getOrCreate()

In [139]:
df = spark.createDataFrame(pdf, ["user", "item", "rating"])

In [140]:
df.count()

25

In [141]:
df.show(df.count())

+----+----+------+
|user|item|rating|
+----+----+------+
| 0.0| 0.0|   5.0|
| 0.0| 1.0|   2.0|
| 0.0| 2.0|   0.0|
| 0.0| 3.0|   4.0|
| 0.0| 4.0|   3.0|
| 1.0| 0.0|   3.0|
| 1.0| 1.0|   1.0|
| 1.0| 2.0|   2.0|
| 1.0| 3.0|   4.0|
| 1.0| 4.0|   0.0|
| 2.0| 0.0|   2.0|
| 2.0| 1.0|   0.0|
| 2.0| 2.0|   1.0|
| 2.0| 3.0|   4.0|
| 2.0| 4.0|   0.0|
| 3.0| 0.0|   2.0|
| 3.0| 1.0|   0.0|
| 3.0| 2.0|   4.0|
| 3.0| 3.0|   3.0|
| 3.0| 4.0|   5.0|
| 4.0| 0.0|   4.0|
| 4.0| 1.0|   0.0|
| 4.0| 2.0|   5.0|
| 4.0| 3.0|   4.0|
| 4.0| 4.0|   0.0|
+----+----+------+



Spark 추천에서는 Rating을 사용할 수 있다.
사용자, 제품, 평가 항목으로 구성한다.

In [ ]:
from pyspark.mllib.recommendation import Rating
Rating(1, 2, 5.0)

#### ALS

In [142]:
from pyspark.ml.recommendation import ALS

als = ALS(rank=10, maxIter=5, seed=0,
         userCol="user", itemCol="item", ratingCol="rating")
model = als.fit(df)

userFactors는 id, features를 저장한 DataFrame

In [143]:
model.userFactors.orderBy("id").collect()

[Row(id=0, features=[-0.5429633855819702, 0.6207461357116699, 0.00924240704625845, 1.2102508544921875, -1.0208851099014282, -0.18855473399162292, -0.2508034110069275, -0.25282663106918335, 0.31892454624176025, 0.61822509765625]),
 Row(id=1, features=[-0.5668818950653076, 0.12327904999256134, 0.04986836761236191, 0.37976983189582825, 0.06874297559261322, 0.30471041798591614, -0.27429163455963135, 0.08352810144424438, 0.9075737595558167, 0.0063494243659079075]),
 Row(id=2, features=[-0.08556553721427917, 0.07655558735132217, 0.6382700800895691, 0.3109457790851593, 0.010670945048332214, 0.45058292150497437, -0.09058509767055511, 0.19691763818264008, 0.9984103441238403, 0.022852005437016487]),
 Row(id=3, features=[0.16086862981319427, 0.20828032493591309, 0.6996798515319824, 0.018300699070096016, 0.11741456389427185, -0.689202606678009, -1.644841194152832, -0.3695868253707886, -0.22651945054531097, 0.3668602705001831]),
 Row(id=4, features=[-1.141239881515503, -0.3533894419670105, -0.22016

In [144]:
test = spark.createDataFrame([(0, 2), (1, 0), (2, 0)], ["user", "item"])

In [145]:
test.show()

+----+----+
|user|item|
+----+----+
|   0|   2|
|   1|   0|
|   2|   0|
+----+----+



In [146]:
predictions = sorted(model.transform(test).collect(), key=lambda r: r[0])

In [150]:
for p in predictions:
    print ("p: {}".format(p))

p: Row(user=0, item=2, prediction=0.23296821117401123)
p: Row(user=1, item=0, prediction=3.1151721477508545)
p: Row(user=2, item=0, prediction=2.069427490234375)


#### 평가

In [151]:
from pyspark.ml.evaluation import RegressionEvaluator

evaluator=RegressionEvaluator(metricName="rmse",labelCol="rating",predictionCol="prediction")

In [152]:
predictions=model.transform(df)
rmse=evaluator.evaluate(predictions)
print("RMSE="+str(rmse))
predictions.show()

RMSE=0.19650942183623138
+----+----+------+-----------+
|user|item|rating| prediction|
+----+----+------+-----------+
| 1.0| 1.0|   1.0|  0.6354888|
| 3.0| 1.0|   0.0|0.037956193|
| 4.0| 1.0|   0.0| 0.13583153|
| 2.0| 1.0|   0.0|   0.269733|
| 0.0| 1.0|   2.0|  1.8882259|
| 1.0| 3.0|   4.0|  3.8084145|
| 3.0| 3.0|   3.0|   2.972996|
| 4.0| 3.0|   4.0|   4.084878|
| 2.0| 3.0|   4.0|  3.6509373|
| 0.0| 3.0|   4.0|  4.0144367|
| 1.0| 4.0|   0.0|  0.1423023|
| 3.0| 4.0|   5.0|   4.652516|
| 4.0| 4.0|   0.0| 0.17499793|
| 2.0| 4.0|   0.0|0.065786414|
| 0.0| 4.0|   3.0|  2.8596754|
| 1.0| 2.0|   2.0|  1.9158916|
| 3.0| 2.0|   4.0|   3.826828|
| 4.0| 2.0|   5.0|  4.7351074|
| 2.0| 2.0|   1.0|   1.149065|
| 0.0| 2.0|   0.0| 0.23296821|
+----+----+------+-----------+
only showing top 20 rows



## S.10 SVD

SVD는 어떤 매트릭스라도 3개의 매트릭스로 분할하는 것을 말한다.
예를 들어 57은 1 3 19 

A = U D V.T
m x n = m x r  r x r  r x n

3 x 2 = 3 x 3  3 x 2  2 x 2


* U 사용자 x latent factors
* S는 대각선 매트릭스로 latent factor의 강도를 표현
* V는 상품 x latent factors

https://alyssaq.github.io/2015/20150426-simple-movie-recommender-using-svd/

In [44]:
from scipy.sparse import csc_matrix
from scipy.sparse.linalg import svds
A = csc_matrix([[1, 0, 0], [5, 0, 2], [0, -1, 0], [0, 0, 3]], dtype=float)
u, s, vt = svds(A, k=2) # k is the number of factors
s #array([ 2.75193379,  5.6059665 ])

array([2.75193379, 5.6059665 ])

In [48]:
import numpy as np
R = np.array([
     [5,3,0,1],
     [4,0,0,1],
     [1,1,0,5],
     [1,0,0,4],
     [0,1,5,4],
    ])

사용자 평점의 평균은 행으로 구한다.

In [51]:
rowMean=np.mean(R, 1)
np.asarray(rowMean)

array([2.25, 1.25, 1.75, 1.25, 2.5 ])

In [52]:
rowMean.shape=(5,1)

In [54]:
normalisedR=R - rowMean
normalisedR

array([[ 2.75,  0.75, -2.25, -1.25],
       [ 2.75, -1.25, -1.25, -0.25],
       [-0.75, -0.75, -1.75,  3.25],
       [-0.25, -1.25, -1.25,  2.75],
       [-2.5 , -1.5 ,  2.5 ,  1.5 ]])

In [55]:
A = normalisedR/ np.sqrt(R.shape[0] - 1)
A

array([[ 1.375,  0.375, -1.125, -0.625],
       [ 1.375, -0.625, -0.625, -0.125],
       [-0.375, -0.375, -0.875,  1.625],
       [-0.125, -0.625, -0.625,  1.375],
       [-1.25 , -0.75 ,  1.25 ,  0.75 ]])

In [56]:
U, D, V=np.linalg.svd(A)
U.shape,D.shape,V.shape

((5, 5), (4,), (4, 4))

In [57]:
V

array([[-0.71493407, -0.21981658,  0.42453521,  0.51021544],
       [-0.20568993,  0.27108679,  0.63140444, -0.6968013 ],
       [ 0.44335192, -0.79258604,  0.4136403 , -0.06440618],
       [ 0.5       ,  0.5       ,  0.5       ,  0.5       ]])

In [58]:
import numpy as np
A = np.array([[7, 2], [3, 4], [5, 3]])
U, D, V = np.linalg.svd(A)
U

array([[-0.69366543,  0.59343205, -0.40824829],
       [-0.4427092 , -0.79833696, -0.40824829],
       [-0.56818732, -0.10245245,  0.81649658]])

## 문제 S-5: ALS 알고리즘으로 영화 추천

### 문제

함께 영화를 보러 간다고 하자.
어떤 영화를 볼까? 묻지 않고 영화를 고르면 좋아할까?
그렇다면 어떤 영화를 좋아하는지 직접 묻지 않고 어떻게 알 수 있을까?
영화에 대한 선호도를 모른다 하더라도, 추정할 수 있는 방법이 있다.
추천 알고리즘인 Matrix Factorization을 푸는 방식으로 ALS Alternating Least Squares를 추천해 보자.

참조: [spark recommendation](https://www.codementor.io/spark/tutorial/building-a-recommender-with-apache-spark-python-example-app-part1)

* 주 13 - spark 추천 영화 음악? 
    * amazon similarity lookup http://blogs.gartner.com/martin-kihn/how-to-build-a-recommender-system-in-python/
    * https://www.codementor.io/spark/tutorial/building-a-web-service-with-apache-spark-flask-example-app-part2
    * https://github.com/grahamjenson/list_of_recommender_systems
        * content-based filtering
        * collaborative filtering


## IPython Notebook에서 SparkSession 생성하기

Jupyter Notebook에서 Spark를 사용하려면 몇 가지 설정이 필요하다.
Spark 실행에 필요한 라이브러리를 경로에서 찾을 수 있게 설정해야 한다.
아래와 같이 ```sys.path.insert()``` 함수를 사용하면 라이브러리를 Python 경로에 추가할 수 있다.

In [1]:
import os
import sys 
os.environ["SPARK_HOME"]=os.path.join(os.environ['HOME'],'Downloads','spark-2.0.0-bin-hadoop2.7')
os.environ["PYLIB"]=os.path.join(os.environ["SPARK_HOME"],'python','lib')
sys.path.insert(0,os.path.join(os.environ["PYLIB"],'py4j-0.10.1-src.zip'))
sys.path.insert(0,os.path.join(os.environ["PYLIB"],'pyspark.zip'))

In [4]:
import pyspark
myConf=pyspark.SparkConf()
spark = pyspark.sql.SparkSession.builder\
    .master("local")\
    .appName("myApp")\
    .config(conf=myConf)\
    .getOrCreate()

## 데이터

사용자의 영화에 대한 평가가 저장되어 있는 ```ratings```, 영화정보를 가지고 있는 ```movies``` 파일을 읽어서, RDD를 생성한다.

### ratings

```ratings```는 사용자, 영화, 평점, 시간 정보를 가지고 있는데, 이 파일을 읽어보자.

In [14]:
import os
small_ratings = os.path.join('data', 'ml-latest-small', 'ratings.csv')

RDD는 sparkContext의 ```textFile(파일)``` 함수로부터 생성한다.
보통 파일은 헤더와 내용으로 구성된다. 첫 줄을 읽어서, 데이터 헤더를 확인하자.

In [34]:
small_ratings_rdd = spark.sparkContext.textFile(small_ratings)

In [35]:
print small_ratings_rdd.take(1)

[u'userId,movieId,rating,timestamp']


In [36]:
small_ratings_rdd_header = small_ratings_rdd.take(1)

In [37]:
print small_ratings_rdd_header[0]

userId,movieId,rating,timestamp


파일의 첫째 줄이 header이므로 이를 ```filter()```한다.
데이터는 4개의 컬럼으로 구성된다. 이를 컴마로 분리하고 처음 3개만 RDD로 만든다.


```python
userId,movieId,rating,timestamp
1,16,4.0,1217897793
1,24,1.5,1217895807
1,32,4.0,1217896246
...
```

아래 ```cache()``` 함수는 필요한 경우에 사용한다.
RDD는 lazy 연산을 한다. ```collect()```, ```count()``` 등과 같은 action 함수와 같이, 실제 데이터로부터 연산이 필요하기 전까지는 lazy 연산을 한다. ```cache()``` 함수는 메모리에 올려놓는다는 의미이다. cache는 연산이 일어나면 메모리에 데이터를 올려놓고, 다음부터 그 cache에 저장된 것을 사용하게 되므로 빠르다.


In [7]:
small_ratings_data = small_ratings_rdd\
    .filter(lambda line: line!=small_ratings_rdd_header)\
    .map(lambda line: line.split(","))\
    .map(lambda tokens: (tokens[0],tokens[1],tokens[2]))\
    .cache()

In [8]:
small_ratings_data.take(3)

[(u'1', u'16', u'4.0'), (u'1', u'24', u'1.5'), (u'1', u'32', u'4.0')]

이를 ```csvRdd()``` 함수로 만들어 ratings, movies 데이터를 만들어 보자.

RDD는 lazy 연산을 한다. ```collect()```, ```count()``` 등과 같은 action 함수와 같이, 실제 데이터로부터 연산이 필요하기 전까지는 lazy 연산을 한다. ```cache()``` 함수는 메모리에 올려놓는다는 의미이다. cache는 연산이 일어나면 메모리에 데이터를 올려놓고, 다음부터 그 cache에 저장된 것을 사용하게 되므로 빠르다.
```cache()```는 필요한 경우에 사용한다.

In [38]:
def csvRdd(csvpath):
    _rdd = spark.sparkContext.textFile(csvpath)
    _rdd_header = _rdd.take(1)[0]
    print "header: %s" % _rdd_header
    rdd = _rdd\
        .filter(lambda line: line!=_rdd_header) \
        .map(lambda line: line.split(",")) \
        .map(lambda tokens: (tokens[0],tokens[1],tokens[2])) \
        .cache()
    return rdd

In [ ]:
#ratingspath = os.path.join(datapath, 'ml-latest-small', 'ratings.csv')
#ratings=csvRdd(ratingspath)
ratings=csvRdd(small_ratings)

In [20]:
ratings.take(3)

header: userId,movieId,rating,timestamp


[(u'1', u'16', u'4.0'), (u'1', u'24', u'1.5'), (u'1', u'32', u'4.0')]

### movies

```movies``` 파일은 영화제목, 장르 정보를 가지고 있다.

In [39]:
moviespath = os.path.join('data', 'ml-latest-small', 'movies.csv')
movies=csvRdd(moviespath)
movies.take(3)

header: movieId,title,genres


[(u'1', u'Toy Story (1995)', u'Adventure|Animation|Children|Comedy|Fantasy'),
 (u'2', u'Jumanji (1995)', u'Adventure|Children|Fantasy'),
 (u'3', u'Grumpier Old Men (1995)', u'Comedy|Romance')]

### train, test

훈련, 테스트 데이터를 분리해 보자. ```randomSplit(weights, seed=None)``` 함수는 weights, seed를 인자로 받는다.
* weights: ```ratings``` 데이터의 분할하는 비율을 설정하고, 정규화해서 합계를 1.0으로 만들어 준다.
* seed: 샘플링하는 숫자

구분 | 비율
-----|-----
train | 6
validation | 2
test | 2

In [22]:
from pyspark.mllib.recommendation import ALS
import math

_train, _validation, _test=ratings.randomSplit([6, 2, 2], seed=0L)

In [23]:
_validation_01 = _validation.map(lambda x: (x[0], x[1]))

In [24]:
_test_01 = _test.map(lambda x: (x[0], x[1]))

### ALS 모델링

ALS는 mllib, ml 패키지 모두 제공되고 있으나, 서로 사용하는 방법이 다르므로 주의가 필요하다.
RDD 기반 API는 Spark 3.0에서는 제외될 예정이다.

```python
#----------------ml package------------------
from pyspark.ml.recommendation import ALS
als = ALS(rank=10, maxIter=20, userCol="user", itemCol="item", ratingCol="rating")
model = als.fit(trainDf)
predictions = model.transform(testDf)

#----------------mllib package----------------
from pyspark.mllib.recommendation import ALS
model = ALS.train(trainRdd, 10, seed=3, iterations=20)
predictions = model.predictAll(testRdd).map(lambda r: (r.user, r.product, r.rating))
```



ALS는 mllib, ml 패키지 모두 제공되고 있으나, 서로 사용하는 방법이 다르므로 주의가 필요하다.
RDD 기반 API는 Spark 3.0에서는 제외될 예정이다.

```python
#----------------ml package------------------
from pyspark.ml.recommendation import ALS
als = ALS(rank=10, maxIter=20, userCol="user", itemCol="item", ratingCol="rating")
model = als.fit(trainDf)
predictions = model.transform(testDf)

#----------------mllib package----------------
from pyspark.mllib.recommendation import ALS
model = ALS.train(trainRdd, 10, seed=3, iterations=20)
predictions = model.predictAll(testRdd).map(lambda r: (r.user, r.product, r.rating))
```

ALS 모델에 필요한 설정이 있다.
* rank는 숨겨진 요인 latent factors의 수
* iterations 반복회수
* lambda는 regularization 계수 (높으면 regularizaton 높음...

In [78]:
seed = 5L
iterations = 10
regularization_parameter = 0.1

errors = [0, 0, 0]
err = 0
tolerance = 0.02

min_error = float('inf')
best_rank = -1
best_iteration = -1

rank=4
# start for
# ranks = [4, 8, 12]
# for rank in ranks:
model = ALS.train(_train,rank,seed=seed,iterations=iterations,lambda_=0.1)

### 예측

#### 전체

```predictAll()``` 함수는 ```ratings``` 평가점수를 예측한다. 즉 사용자의 영화에 대한 평가점수가 없는 경우, 몇 점인지 예측하게 된다.

In [79]:
predictions = model.predictAll(_validation_01)

predictions은 RDD이므로, 예측 결과 값은 아래와 같이 ```take()```, ```collect()``` 함수를 바로 사용하거나, ```map()``` 함수를 사용해서 추출할 수 있다.

In [80]:
type(predictions)

pyspark.rdd.RDD

In [81]:
predictions.take(2)

[Rating(user=475, product=81132, rating=1.208942277934203),
 Rating(user=469, product=667, rating=2.287210521555096)]

In [82]:
predictions.map(lambda r: ((r[0], r[1]), r[2])).take(2)

[((475, 81132), 1.208942277934203), ((469, 667), 2.287210521555096)]

실제와 예측을 나란히 비교해 보자.
먼저 예측을 저장하고, 이를 ```map()``` 함수로 실제 값을 출력하고 ```join()``` 함수로 나란히 출력해 보자.

In [83]:
predictions=predictions.map(lambda r: ((r[0], r[1]), r[2]))

In [84]:
rates_and_preds = _validation\
    .map(lambda r: ((int(r[0]), int(r[1])), float(r[2])))\
    .join(predictions)

In [85]:
rates_and_preds.take(3)

[((627, 30793), (3.5, 3.3273636051642086)),
 ((668, 4030), (1.5, 1.8208563455773858)),
 ((332, 2528), (4.0, 4.088212813873781))]

In [88]:
model.userFeatures()

PythonRDD[1214] at RDD at PythonRDD.scala:48

#### 사용자별 예측

userId, moveId를 넣으면, 평가점수를 예측할 수 있다.
예를 들어, 1번 사용자, 24번 영화에 대한 rating은 약 2.04이다.

In [70]:
model.predict(1,24)

2.477817297611674

* 1번 사용자, 상위 10개 상품 추천

In [92]:
top10for1 = model.recommendProducts(1,10)

In [93]:
type(top10for1)

list

In [94]:
top10for1

[Rating(user=1, product=5147, rating=5.417326172972089),
 Rating(user=1, product=3272, rating=5.272865359188067),
 Rating(user=1, product=103980, rating=5.221125234610412),
 Rating(user=1, product=90603, rating=5.199192419824584),
 Rating(user=1, product=6583, rating=5.131635645196752),
 Rating(user=1, product=105844, rating=5.127320038146992),
 Rating(user=1, product=714, rating=5.094333621153465),
 Rating(user=1, product=917, rating=5.076105430608997),
 Rating(user=1, product=59810, rating=5.037403608152832),
 Rating(user=1, product=104177, rating=5.037403608152832)]

In [96]:
top10for1[2][1]

103980

In [99]:
movies.lookup

<bound method PipelinedRDD.lookup of PythonRDD[273] at RDD at PythonRDD.scala:48>

### 오류

MSE Mean Squared Error을 출력해보자.

In [90]:
error = math.sqrt(rates_and_preds
                  .map(lambda r: (r[1][0]-r[1][1])**2)\
                  .mean()
                 )

In [91]:
print error

0.919837162894
